name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_BUILDKIT: 1
      run: docker build . --file .devcontainer/Dockerfile --tag go-base:$(date +%s)
